# Stage 1: Build the Angular application
FROM node:20.19 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install -f
RUN npm install @angular/animations
COPY . .
RUN npm run build --prod

# Stage 2: Serve the application using NGINX
FROM nginx:alpine
COPY --from=build /app/dist/rfq-system /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
