name: Deploy RFQSubmission Services

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Create Docker network
      run: docker network create rfq-network || true

    - name: Stop and remove existing backend containers
      run: |
        docker stop rfqsubmission_api rfqsubmission_worker rfqsubmission_emailservice rfqsubmission_notificationservice || true
        docker rm rfqsubmission_api rfqsubmission_worker rfqsubmission_emailservice rfqsubmission_notificationservice || true
        docker rmi rfqsubmission/api rfqsubmission/worker rfqsubmission/emailservice rfqsubmission/notificationservice || true
      continue-on-error: true

    - name: Create named volumes if not exist
      run: |
        docker volume create rfqsubmission_media_data || true
        docker volume create rfqsubmission_documents_data || true
        docker volume create rfqsubmission_kibana_config || true
        docker volume create rfqsubmission_elasticsearch_data || true
        docker volume create postgres_data || true

    - name: Start infrastructure containers if missing
      run: |
        # Postgres
        docker ps -a --format '{{.Names}}' | grep -qw rfqsubmission_postgres || \
        docker run -d --name rfqsubmission_postgres --hostname rfqsubmission-postgres-host \
          --network rfq-network \
          -e POSTGRES_USER=admin \
          -e POSTGRES_PASSWORD=passw123 \
          -e POSTGRES_DB=rfqsubmission \
          -v postgres_data:/var/lib/postgresql/data \
          -p 5432:5432 \
          postgres:14

        # RabbitMQ
        docker ps -a --format '{{.Names}}' | grep -qw rfqsubmission_rabbitmq || \
        docker run -d --name rfqsubmission_rabbitmq --hostname rfqsubmission-rabbitmq-host \
          --network rfq-network \
          -e RABBITMQ_DEFAULT_USER=admin \
          -e RABBITMQ_DEFAULT_PASS=passw123 \
          -e RABBITMQ_DEFAULT_VHOST=/ \
          -p 5672:5672 -p 15672:15672 \
          rabbitmq:3.11-management

        # Redis
        docker ps -a --format '{{.Names}}' | grep -qw rfqsubmission_redis || \
        docker run -d --name rfqsubmission_redis --network rfq-network -p 6379:6379 redis:latest

        # Elasticsearch
        docker ps -a --format '{{.Names}}' | grep -qw rfqsubmission_elasticsearch || \
        docker run -d --name rfqsubmission_elasticsearch --network rfq-network \
          -e discovery.type=single-node \
          -e xpack.security.enabled=false \
          -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
          -v rfqsubmission_elasticsearch_data:/usr/share/elasticsearch/data \
          -p 9202:9200 \
          docker.elastic.co/elasticsearch/elasticsearch:7.17.4

        # Kibana
        docker ps -a --format '{{.Names}}' | grep -qw rfqsubmission_kibana || \
        docker run -d --name rfqsubmission_kibana --network rfq-network \
          -v rfqsubmission_kibana_config:/usr/share/kibana/config \
          -p 5605:5601 \
          docker.elastic.co/kibana/kibana:7.17.4

    - name: Build and run backend services
      run: |
        export ASPNETCORE_ENVIRONMENT=Production

        # Build API
        docker build -t rfqsubmission/api -f rfq-api/src/Api/Dockerfile ./rfq-api

        # Build Worker
        docker build -t rfqsubmission/worker -f rfq-api/src/Worker/Dockerfile ./rfq-api

        # Build EmailService
        docker build -t rfqsubmission/emailservice -f rfq-api/src/EmailService/Dockerfile ./rfq-api

        # Build NotificationService
        docker build -t rfqsubmission/notificationservice -f rfq-api/src/NotificationService/Dockerfile ./rfq-api

        # Run API
        docker run -d \
          --name rfqsubmission_api \
          --network rfq-network \
          -p 8090:80 \
          --restart unless-stopped \
          -v rfqsubmission_media_data:/app/media \
          -v rfqsubmission_documents_data:/app/documents \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -e ConnectionStrings__Default="Host=rfqsubmission-postgres-host;Port=5432;Database=rfqsubmission;Username=admin;Password=passw123" \
          rfqsubmission/api

        # Run Worker
        docker run -d \
          --name rfqsubmission_worker \
          --network rfq-network \
          --restart unless-stopped \
          -e ASPNETCORE_ENVIRONMENT=Production \
          rfqsubmission/worker

        # Run EmailService
        docker run -d \
          --name rfqsubmission_emailservice \
          --network rfq-network \
          --restart unless-stopped \
          -e ASPNETCORE_ENVIRONMENT=Production \
          rfqsubmission/emailservice

        # Run NotificationService
        docker run -d \
          --name rfqsubmission_notificationservice \
          --network rfq-network \
          -p 8091:80 \
          --restart unless-stopped \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -e ASPNETCORE_URLS=http://+:80 \
          rfqsubmission/notificationservice
