# .github/workflows/deploy-api.yml
name: Deploy .NET Core API

on:
  push:
    branches: [ development ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Stop existing container
      run: |
        docker stop rfq-api || true
        docker rm rfq-api || true
        docker rmi rfq/api || true
      continue-on-error: true
    
    - name: Build .NET Core Docker image
      run: |
        cd backend
        docker build -t rfq/api .
    
    - name: Run API container
      run: |
        docker run -d \
          --name rfq-api \
          --network rfq-network \
          -p 8090:80 \
          --restart unless-stopped \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -e ConnectionStrings__DefaultConnection="Host=postgres;Database=rfqsubmission;Username=rfquser;Password=your_postgres_password" \
          -e ConnectionStrings__Redis="redis:6379" \
          -e ConnectionStrings__Elasticsearch="http://elasticsearch:9200" \
          -e ConnectionStrings__RabbitMQ="amqp://rfquser:your_rabbitmq_password@rabbitmq:5672/" \
          rfq/api
